exports.library = [
{left: ['beautiful','attractive','gorgeous','pretty','nice','stunnning','sexy','elegant'],
right: ['ugly','disgusting','hideous','horrid','grotesque','unsighly','beastly','inelegant']},
{left: ['good','great','wonderful','terrific','amazing','cool','excellent','superb','fantastic','awesome','swell','peachy'],
right: ['bad','terrible','awful','dreadful','lousy','poor','atrocious','aggravating','hellish']},
{left: ['happy','joyful','overjoyed','pleased','excited','elated','glad','cheerful','thrilled'],
right: ['distraught','glum','gloomy','despondent','depressed','sad','dejected','mournful','somber','dismal']},
{left: ['brilliant','bright','brainy','wise','smart','intelligent','cunning','genius','adept','clever','ingenious'],
right: ['stupid','ignorant','dumb','foolish','naive','idiotic','brainless','moronic','simpleminded']},
{left: ['advanced','complex','complicated','inscrutable','subtle','convoluted','labyrinthine','various'],
right: ['simple','effortless','basic','elementary','uncomplicated','straightforwards','inelligible','lucid','piece of cake','plain']},
{left: ['colourful','gaudy','vivid','bright','flashy','vibrant','multicolored','kaleidoscopic','variegated','psychadelic'],
right: ['dull','bland','drab','dreary','colorless','ashen','bleached','cadaverous','ghastly','sickly','uncolored','ashy']},
{left: ['love','enjoy','relish','fancy','revel in','cherish','savor','adore'],
right: ['dislike','hate','detest','lothe','despise','abhor']},
{left: ['strange','unusual','abnormal','rediculous','absurd','crazy','mythical','freakish','weird','silly'],
right: ['normal','usual','common','expected','natural','typical','commonplace','run-of-the-mill','ordinary']},
{left: ['delicious','tasy','delectable','gourmet','yummy','scrumptious'],
right: ['disgusting','gross','vomitous','rotten','disagreeable','nasty','unappetising']},
{left: ['chilren','son','daughter','dog','horse','cat','dogs','cats','family','mother','father','kids','parents','grandma','grandpa'],
right: ['rats','worms','wolves','muskrats','otter','snakehead fish','baboon','weasel']},
{left: ['soccer','football','basketball','hockey','wrestling'],
right: ['tiddlywinks','slappybottom','wrasslin\'','opera','auction','beatdown']},
{left: ['beer','wine','vodka','rum','whisky','margarita','tea','cocktail','smoothie','soda','water'],
right: ['urine','sweat','rain water','soil','angel\'s tears','battery acid','saline solution','pus','ovaltine']},
{left: ['school','bar','store','show','house','gym','work'],
right: ['jail','psych ward','jello factory','zoo','comic store','nerd convention']},
{left: ['run','talk','laugh','dance','sing','drink','eat','listen','go','walk','breathe','do','win','lose'],
right: ['fart','ooze','flap','undulate','slurp','suckle','squish','burp','explode','lick']},
{left: ['running','talking','laughing','dancing','singing','drinking','eating','listening','going','walking','breathing','doing','winning','losing'],
right: ['farting','oozing','flapping','undulating','slurping','suckling','squishing','burping','exploding']},
{left: ['fun','exciting','enjoyable','stimulating','thrilling','pleasant','hilarious'],
right: ['boring','woeful','heinous','draining','humdrum','unfunny','stodgy','lifeless','excruciating']},
{left: ['chicken','steak','salad','sandwich','bread','rice','veggies','vegetables','sushi','salmon','tuna','burrito','fruit','bananas'],
right: ['grubs','sugar cane','chewing tabacco','hay','coal tar waste','paste','tylenol','hedge clippings','crickets','centipede']},
{left: ['red','green','blue','black','white','orange','purple','yellow','brown'],
right: ['itchy','fudge colored','clear','x-ray','bubble-gum','glowing','radioactive','oozing']},
{left: ['television','x-box','nintendo','cellphone','computer','laptop','table'],
right: ['fart machine','whipping block','squirrel cage','horse tickler','meat grinder','sausage stuffer','alien embryo','atari']},
{left: ['really','very','extremely','super','especially','particularly'],
right: ['literally','not','infinitesimally','microscopically','barely','hardly','poopingly']},
{left: ['hand','nose','mouth','foot','leg','legs','ears','eyes','tongue','cheek','earlobe'],
right: ['stomache','chest','butt','face','lips','arm','arms','epidermis','fingernail','weenis']},
{left: ['small','medium','large','huge','tiny','big'],
right: ['ginormous','friggin huge','runty','piddling','itty bitty','scruptious','thick','peanut sized','wee','teensy-weensy','super big like WOW']}
]